In [33]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

In [34]:
df= pd.read_csv('Training.csv')

In [35]:
df

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis,Unnamed: 133
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo,NaN
4916,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,Acne,NaN
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Urinary tract infection,NaN
4918,0,1,0,0,0,0,1,0,0,0,...,0,1,1,1,1,0,0,0,Psoriasis,NaN
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,Impetigo,NaN

In [36]:
le = LabelEncoder()
df["prognosis"]= le.fit_transform(df["prognosis"])
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis,Unnamed: 133
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN

In [37]:
df

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis,Unnamed: 133
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
4916,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,2,NaN
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,38,NaN
4918,0,1,0,0,0,0,1,0,0,0,...,0,1,1,1,1,0,0,0,35,NaN
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,27,NaN

In [46]:
df = df.drop(columns=['Unnamed: 133'])
display(df.head())

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15

In [40]:
precautions = pd.read_csv("symptom_precaution.csv")
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis,Unnamed: 133
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,NaN

In [48]:
print(precautions.info())
print('\nMissing values in precautions DataFrame:')
print(precautions.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Disease       41 non-null     object
 1   Precaution_1  41 non-null     object
 2   Precaution_2  41 non-null     object
 3   Precaution_3  40 non-null     object
 4   Precaution_4  40 non-null     object
dtypes: object(5)
memory usage: 1.7+ KB
None

Missing values in precautions DataFrame:
Disease         0
Precaution_1    0
Precaution_2    0
Precaution_3    1
Precaution_4    1
dtype: int64

In [49]:
precautions = precautions.drop(columns=['Precaution_3', 'Precaution_4'])
print(precautions.info())
print('\nMissing values in precautions DataFrame:')
print(precautions.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Disease       41 non-null     object
 1   Precaution_1  41 non-null     object
 2   Precaution_2  41 non-null     object
dtypes: object(3)
memory usage: 1.1+ KB
None

Missing values in precautions DataFrame:
Disease         0
Precaution_1    0
Precaution_2    0
dtype: int64

In [50]:
display(df.head())

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15

In [55]:
selected_columns = ['itching', 'shivering', 'acidity', 'stomach_pain', 'vomiting', 'fatigue', 'joint_pain', 'high_fever', 'dehydration', 'headache', 'cough', 'prognosis']
df_filtered = df[selected_columns]
display(df_filtered.head())

,itching,shivering,acidity,stomach_pain,vomiting,fatigue,joint_pain,high_fever,dehydration,headache,cough,prognosis
0,1,0,0,0,0,0,0,0,0,0,0,15
1,0,0,0,0,0,0,0,0,0,0,0,15
2,1,0,0,0,0,0,0,0,0,0,0,15
3,1,0,0,0,0,0,0,0,0,0,0,15
4,1,0,0,0,0,0,0,0,0,0,0,15

In [56]:
X_filtered = df_filtered.drop('prognosis', axis=1)
y_filtered = df_filtered['prognosis']

model_filtered = DecisionTreeClassifier()
model_filtered.fit(X_filtered, y_filtered)

print(f"Model retrained with {len(X_filtered.columns)} selected symptoms.")

Model retrained with 11 selected symptoms.

In [57]:
def chatbot_():
    print("\n🩺 SMART MEDICAL ANALYSIS CHATBOT (Filtered Symptoms)")
    print("Answer symptoms with YES or NO\n")

    symptoms = {}

    for column in X_filtered.columns:
        ans = input(f"Do you have {column}? (yes/no): ").lower()
        symptoms[column] = 1 if ans == "yes" else 0

    input_data = pd.DataFrame([symptoms])

    prediction_code = model_filtered.predict(input_data)[0]
    predicted_disease = le.inverse_transform([prediction_code])[0]
    print("\n✅ Possible Disease:", predicted_disease)

    # Lookup precautions
    precaution_info = precautions[precautions["Disease"] == predicted_disease]
    if not precaution_info.empty:
        precaution_1 = precaution_info["Precaution_1"].values[0]
        precaution_2 = precaution_info["Precaution_2"].values[0]
        print("💊 Suggested Precaution 1:", precaution_1)
        print("💊 Suggested Precaution 2:", precaution_2)
    else:
        print("No specific precautions found for this disease.")

chatbot_()

🩺 SMART MEDICAL ANALYSIS CHATBOT (Filtered Symptoms)
Answer symptoms with YES or NO

Do you have itching? (yes/no): yes
Do you have shivering? (yes/no): no
Do you have acidity? (yes/no): no
Do you have stomach_pain? (yes/no): yes
Do you have vomiting? (yes/no): no
Do you have fatigue? (yes/no): yes
Do you have joint_pain? (yes/no): yes
Do you have high_fever? (yes/no): no
Do you have dehydration? (yes/no): yes
Do you have headache? (yes/no): yes
Do you have cough? (yes/no): no

✅ Possible Disease: Dengue
💊 Suggested Precaution 1: drink papaya leaf juice
💊 Suggested Precaution 2: avoid fatty spicy food